
#Dynamic Lights Settings
[Settings]

	[Settings."Lighting Settings"]
		#Allowed Values: OFF, SLOW, FAST, REALTIME
		"Quality Mode (OFF, SLOW, FAST, REALTIME)" = "REALTIME"
		"Dynamic Entity Lighting" = false
		"Dynamic TileEntity Lighting" = false
		"Only Update On Position Change" = true

